services:
  db:
    image: postgres:16-alpine
    container_name: inventory-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventory || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
      dockerfile: src/inventory-api/Dockerfile
    container_name: inventory-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      # L'API écoute en HTTP interne, Nginx fait le TLS devant
      ASPNETCORE_URLS: http://+:8080
      # Connexion DB (si tu n'as rien d'autre dans ton appsettings.json)
      ConnectionStrings__Default: Host=db;Port=5432;Database=inventory;Username=postgres;Password=postgres
    expose:
      - "8080"

  web:
    build:
      context: .
      dockerfile: src/inventory-web/Dockerfile
    container_name: inventory-web
    depends_on:
      - api
    environment:
      # IMPORTANT : mets l’IP privée de ton serveur ici, c'est ce qui finira dans le certificat
      PUBLIC_HOST: ${PUBLIC_HOST}
    ports:
      - "80:80"
      - "443:443"

volumes:
  dbdata:
