services:
  api:
    ports:
      - "8080:8080"

  web:
    build:
      context: .
      dockerfile: Dockerfile.inventory-web
      args:
        BASE_REG: public.ecr.aws/docker/library
    depends_on:
      - api

  db:
    ports:
      - "5432:5432"
