services:
  api_green:
    build:
      context: .
      dockerfile: src/inventory-api/Dockerfile
    container_name: inventory-api-green
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_DETAILEDERRORS: "false"
      APPLY_MIGRATIONS: "true"
      DISABLE_MIGRATIONS: "false"
      AppSettings__SeedOnStartup: "false"
      DISABLE_SERILOG: "false"
      ASPNETCORE_URLS: http://0.0.0.0:8080
      AppSettings__CatalogEndpointsPublic: "true"
      ConnectionStrings__Default: "Host=db;Port=5432;Database=inventory;Username=postgres;Password=postgres;Include Error Detail=true"
    expose:
      - "8080"
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/health >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
