name: API Integration Tests (self-hosted)

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: api-tests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: [self-hosted, tsf]
    timeout-minutes: 40

    # Permissions minimales + lecture artefacts pour le reporter
    permissions:
      contents: read
      checks: write

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: inv_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      TEST_DB_CONNECTION: Host=localhost;Port=5432;Database=inv_test;Username=postgres;Password=postgres
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - uses: actions/checkout@v4

      # 👇 Pas d’expression ${{ runner.temp }} dans le YAML (VS Code content)
      - name: Prepare .NET locations
        run: |
          echo "DOTNET_INSTALL_DIR=$RUNNER_TEMP/.dotnet" >> "$GITHUB_ENV"
          echo "DOTNET_ROOT=$RUNNER_TEMP/.dotnet" >> "$GITHUB_ENV"
          echo "$RUNNER_TEMP/.dotnet" >> "$GITHUB_PATH"
          echo "$RUNNER_TEMP/.dotnet/tools" >> "$GITHUB_PATH"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      # Attente Postgres (pas besoin du client psql sur le runner)
      - name: Wait for Postgres service
        run: |
          for i in {1..30}; do
            (echo > /dev/tcp/127.0.0.1/5432) >/dev/null 2>&1 && exit 0
            echo "Waiting for Postgres... ($i/30)"; sleep 2
          done
          echo "Postgres not ready"; exit 1

      - name: Test (all)
        run: |
          mkdir -p tests/inventory.api.tests/TestResults
          dotnet test tests/inventory.api.tests/CineBoutique.Inventory.Api.Tests.csproj \
            -c Release --no-build \
            --logger "trx;LogFileName=test_results.trx" \
            --results-directory tests/inventory.api.tests/TestResults

      # Annotation des échecs de tests dans l'onglet Checks (UX ++)
      - name: Publish test report (TRX)
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: API Tests
          path: tests/inventory.api.tests/TestResults/**/*.trx
          reporter: dotnet-trx
          fail-on-error: false  # laisse le job échouer sur l’étape test, pas ici

      - name: Upload raw TRX
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-trx
          path: tests/inventory.api.tests/TestResults
