name: API Integration Tests (self-hosted)

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: api-tests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: [self-hosted, tsf, Linux, X64]
    timeout-minutes: 40

    permissions:
      contents: read
      checks: write

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: inv_test
        # Port hôte fixe pour éviter les expressions job.services[...] (qui faisaient râler le linter)
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=30

    env:
      # === Env de test : traces détaillées et logs console ===
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DISABLE_SERILOG: "true"

      # === Connexion DB (service Postgres ci-dessus) ===
      TEST_DB_CONNECTION: Host=127.0.0.1;Port=5432;Database=inv_test;Username=postgres;Password=postgres

    steps:
      - uses: actions/checkout@v4

      # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      # Forcer l'installation .NET dans un répertoire user-writable
      - name: Prepare .NET install dir (user-writable)
        run: |
          echo "DOTNET_INSTALL_DIR=$HOME/.dotnet" >> "$GITHUB_ENV"
          echo "DOTNET_ROOT=$HOME/.dotnet"        >> "$GITHUB_ENV"
          mkdir -p "$HOME/.dotnet"
      # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        env:
          DOTNET_INSTALL_DIR: ${{ env.DOTNET_INSTALL_DIR }}  # évite /usr/share/dotnet
        with:
          dotnet-version: '8.0.x'
          cache: true

      # (optionnel mais utile en self-hosted) on s'assure que le PATH est OK et on log l'info
      - name: Verify dotnet
        run: |
          echo "${DOTNET_INSTALL_DIR}" >> "$GITHUB_PATH"
          echo "${DOTNET_INSTALL_DIR}/tools" >> "$GITHUB_PATH"
          dotnet --info

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Wait for Postgres service
        run: |
          for i in {1..60}; do
            (echo > /dev/tcp/127.0.0.1/5432) >/dev/null 2>&1 && exit 0
            echo "Waiting for Postgres... ($i/60)"; sleep 1
          done
          echo "Postgres not ready"; exit 1

      - name: Test (API)
        env:
          TEST_DB_CONNECTION: ${{ env.TEST_DB_CONNECTION }}
        run: |
          mkdir -p tests/inventory.api.tests/TestResults
          dotnet test tests/inventory.api.tests/CineBoutique.Inventory.Api.Tests.csproj \
            -c Release --no-build \
            --logger "trx;LogFileName=test_results.trx" \
            --logger "console;verbosity=detailed" \
            --results-directory tests/inventory.api.tests/TestResults

      - name: Publish test report (TRX)
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: API Tests
          path: tests/inventory.api.tests/TestResults/**/*.trx
          reporter: dotnet-trx
          fail-on-error: false

      - name: Upload artifacts (TRX + logs éventuels)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-artifacts
          path: |
            tests/inventory.api.tests/TestResults
            **/logs/**
            **/TestResults/**
