name: CI & Deploy (to deploy branch)

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: write   # nécessaire pour pousser sur la branche deploy
  packages: read

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore CineBoutique.Inventory.sln

      - name: Build
        run: dotnet build CineBoutique.Inventory.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test CineBoutique.Inventory.sln --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/inventory-web
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'src/inventory-web/package-lock.json'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build

  deploy-branch:
    name: Update "deploy" branch when CI is green
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Force-update deploy branch to this commit
        run: |
          # Crée ou avance la branche 'deploy' exactement sur le commit courant
          git push origin HEAD:refs/heads/deploy --force
          echo "Branch 'deploy' is now at $GITHUB_SHA"
