name: Lint Docker Compose

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  lint_compose:
    runs-on: [self-hosted, Linux, X64, tsf, docker]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show Docker & Compose versions
        run: |
          docker version
          docker compose version || true

      - name: Validate docker-compose.yml
        run: docker compose -f docker-compose.yml config > /dev/null
